---
title: "Open and clean WMO data"
author: "Jonathan Bourne"
date: "11. oktober 2015"
output: pdf_document
---

This document will contain the code that can be used to open and the WMO files and extract the data

summaries to take mean, varience total number

Load packages
```{r}

packages <- c("dplyr", "tidyr", "magrittr", "openxlsx", "knitr", "caret")

lapply(packages, library, character.only = TRUE)
select <- dplyr::select #Clash between dplyr and MASS which is loaded bby Caret

file.loc <-file.path("~","Benchmarking", "PA consulting", "2015", "Statkraft") #file location may be computer specific depending on network
setwd(file.loc)
opts_knit$set(root.dir = "C:/Users/Jonno/Documents/Benchmarking/PA consulting/2015/Statkraft")
opts_chunk$get("root.dir")
```

#Extract relevant sheets as data frames

extraction functions
```{r}

powerplant <- function(filename, company) {
  power_plant_level <- read.xlsx(filename, sheet = "T Part A - Power plant level", startRow = 12, colNames = FALSE )[,1:26]
  
  names(power_plant_level) <- read.xlsx(filename, sheet = "T Part A - Power plant level" ,
                                        startRow = 8, rows = 8:9)[,-c(1,27,28)]%>% 
    names  %>% gsub("/|\\-|\\?", "",.)
  power_plant_level %<>% filter(!is.na(Station.ID))
   power_plant_level$Station.ID <- paste(company, power_plant_level$Station.ID, sep = "" )
 names(power_plant_level) <- gsub("\\?","", names(power_plant_level))
  
 names(power_plant_level)[grep("Commisioning", names(power_plant_level))] <- "Age"
  year <-substr(Sys.Date(), 1, 4) %>% as.integer
  power_plant_level %<>% mutate(Age = year-Age)
  power_plant_level
}

gen_spec <- function(filename, company){
gen_spec <- read.xlsx(filename, sheet = "T part B - Spec. generator" , startRow = 12, colNames = FALSE )[,1:16]

names(gen_spec) <-  read.xlsx(filename, sheet = "T part B - Spec. generator" , 
                             startRow = 8, rows = 8:9)[,2:17]%>% 
                    names %>% gsub("\\?|\\/|\\(|\\)", "",.) #the ? are being read as Regex and so are removed from the headings, they could be escaed but are superflous anyway.
gen_spec %<>% filter(!is.na(Station.ID))
gen_spec$Station.ID <- paste(company, gen_spec$Station.ID, sep = "" )
catag <-c("Turbine.type","Reversible.pump.turbine","Turbine.with.2.or.more.runners","Water.cooled.windings")
gen_spec %<>%mutate_each_(funs(factor),catag) %>% 
          group_by(Station.ID) %>% 
          mutate(specID = 1, specID = paste(Station.ID,"_",cumsum(specID),sep="")) %>% 
  ungroup  %>% select(-Comissioning.year.of.station)

 names(gen_spec)[grep("Comissioning.year.of.generator", names(gen_spec))] <- "Gen.Age"
  year <-substr(Sys.Date(), 1, 4) %>% as.integer
  gen_spec %<>% mutate(Gen.Age = year-Gen.Age)
gen_spec
}

dam_spec <- function(filename, company) {
    dam_spec <- read.xlsx(filename, sheet = "T part C - Spec. reservoir, EBI", startRow = 12, colNames = FALSE )[,c(2,5:10)]

    names(dam_spec) <- read.xlsx(filename, sheet = "T part C - Spec. reservoir, EBI", startRow = 8, rows = 8:9)[,c(2,6:11)]%>% 
      names %>% gsub("\\?|\\/|\\(|\\)", "",.) #the ? are being read as Regex and so are removed from the headings, they could be escaed but are superflous anyway.
    dam_spec %<>% filter(!is.na(Station.ID))
    dam_spec$Station.ID <- paste(company, dam_spec$Station.ID, sep = "" )
    names(dam_spec)[3] <- "Distance_from_roads_geq1"
    catag <- c("Dam.or.Riverstream.intake.EBI","Distance_from_roads_geq1"   ,"Climate.zone" ,"Dam.classification")
    dam_spec %<>% mutate_each_(funs(factor),catag) %>% 
          group_by(Station.ID) %>% 
          mutate(specID = 1, specID = paste(Station.ID,"_",cumsum(specID),sep="")) %>% 
          ungroup 
dam_spec
}

 company <- "Statkraft"
 filename <- "Data Gathering Sheet 2015 V2.xlsx"

gates_spec <- function(filename, company) {
      gates_spec <- read.xlsx(filename, sheet = "T part D - Spec. gates above gr", startRow = 12, colNames = FALSE )[,1:9]

      names(gates_spec) <- read.xlsx(filename, sheet = "T part D - Spec. gates above gr", 
                               startRow = 8, rows = 8:9)[,2:10]%>% names %>% gsub("\\?|\\/", "",.)
      gates_spec %<>% filter(!is.na(Station.ID))
      gates_spec$Station.ID <- paste(company, gates_spec$Station.ID, sep = "" )
#names(gates_spec) <- gsub("\\?","", names(gates_spec))
      gates_spec$Object.ID <- gates_spec$Object.ID[sub(",", "", gates_spec$Object.ID)] # commas were causing problems with the csv import, even though they were strings.
      catag <- c("SectorRadial.gate","Flood.gate")
      gates_spec %<>% mutate_each_(funs(factor),catag) %>% 
          group_by(Station.ID) %>% 
          mutate(specID = 1, specID = paste(Station.ID,"_",cumsum(specID),sep="")) %>% 
          ungroup  
gates_spec
}

valves_spec <- function(filename, company) {
  valves_spec <- read.xlsx(filename, sheet = "T part E - Spec. valves", startRow = 12, colNames = FALSE )[,1:5]

names(valves_spec) <- read.xlsx(filename, sheet = "T part E - Spec. valves", startRow = 8, rows = 8:9)[,2:6]%>% names %>% gsub("\\?", "",.) #the ? are being read as Regex and so are removed from the headings.
valves_spec %<>% filter(!is.na(Station.ID)) #prevents loads of empty lines being imported
valves_spec$Station.ID <- paste(company, valves_spec$Station.ID, sep = "" )
# valves does not have any catagorical values to rollup
valves_spec %<>%  group_by(Station.ID) %>% 
                  mutate(specID = 1, specID = paste(Station.ID,"_",cumsum(specID),sep="")) %>%
                  ungroup 
valves_spec
}

rollup <- function(dataframe){
        dataframe %>% 
              group_by(Station.ID) %>% 
              mutate(count = n()) %>% 
              summarise_each_(funs(mean, max, min, sum, var), 
                  names(.)[sapply(., class)=="numeric"|sapply(., class)=="integer"])
}

catagoricals <- function(data) {
data <-  data %>% select(1,length(.),which(sapply(., class)=="factor"))

#split out catagorical values and replace rogue J's with Y remove NA values
data2 <- data %>% gather(variable, class, -c(Station.ID,specID))
data2$class <- sub("^J$", "Y", data2$class)
data2 %<>%  mutate(present = 1, variable = paste(variable, "_",class, sep="")) %>%
            select(-class) %>% 
            spread(variable, present, fill = 0) %>% select(-specID) %>%
  mutate(x_NA = 1) #this additional column prevents a bug on the next command which is if there area no columns ending in _NA all columns are removed.

data2 %<>% select(-ends_with("_NA"))

##Aggregate up all the values into a single powerplant
data2 %<>% group_by(Station.ID) %>% summarise_each(funs(sum))
}

aggregator <- function(data) {
    if (length(which(sapply(data, class)=="factor"))!=0){  
        rolled <- rollup(data)
        catag <- catagoricals(data)
        data <- full_join(rolled, catag, by = "Station.ID")
  } else {data <- rollup(data)}
    data
}

combinatron <- function(filename, companyname){
plantspec <- powerplant(filename, companyname) #%>% aggregator
genspec <- gen_spec(filename, companyname) %>% aggregator
damspec <- dam_spec(filename, companyname) %>% aggregator
gatespec <- gates_spec(filename, companyname) %>% aggregator
valvespec <- valves_spec(filename, companyname) %>% aggregator
plantspec %<>% full_join(., genspec ,by="Station.ID") %>% 
                full_join(., damspec ,by="Station.ID") %>%
                full_join(., gatespec ,by="Station.ID") %>%
                full_join(.,valvespec,by="Station.ID")
plantspec
}


costjoiner2 <- function(company, costfile){
  cost <-read.xlsx(costfile)[,-c(1:3,5:6)] 
  cost %<>% filter(!is.na(Station.ID)) %>%mutate(Station.ID =paste(company, cost$Station.ID, sep = "" ))
}

```

```{r}
#Load and combine files
Statkraft<- combinatron("Data Gathering Sheet 2015 V2.xlsx","Statkraft" )
ECO <- combinatron("ECO 2014.xlsx", "ECO")
Eidsiva <- combinatron("Eidsiva 2013 DD1 (31.04.2014).xlsx","Eidsiva")

# eidsdam <-dam_spec("Eidsiva 2013 DD1 (31.04.2014).xlsx","Eidsiva")
# company <- "Eidsiva"
# filename <- "Eidsiva 2013 DD1 (31.04.2014).xlsx"
 companyname <- "Statkraft"
 filename <- "Data Gathering Sheet 2015 V2.xlsx"
```

```{r}
#Additional variable removal
techdata <- bind_rows(Statkraft, ECO, Eidsiva) 
techdata[is.na(techdata)] <- 0
techdata %<>% select( 
       -contains("Number.of.StartStop"),
       -Altitude.above.sea.level_sum,
       -Hydraulic.Head_sum, 
       -Rotations.per.minute_sum,
       -WMOInclusion,
       -Air.compression.chamber,
       -contains("Generator.number"),
       -contains("count"),
       -Water.cooled.windings_N,
       -Reversible.pump.turbine_N,
       - Distance_from_roads_geq1_N,
       -Area,
       -Sub.area,
       -Catchment.area,
       -X6,
       -Turbine.with.2.or.more.runners_N) %>% 
  mutate(Water.cooled.windings_Y= (Water.cooled.windings_Y >0),
         Climate.zone_1= (Climate.zone_1 >0),
         Climate.zone_2= (Climate.zone_2 >0),
         Climate.zone_3= (Climate.zone_3 >0),
         Reversible.pump.turbine_Y= (Reversible.pump.turbine_Y >0),
         Distance_from_roads_geq1_Y= (Distance_from_roads_geq1_Y >0),
         Storage..Runofriver.plant=Storage..Runofriver.plant=="R",
         Station.above.ground =Station.above.ground=="Y") 

orig <- c("pure.Hydrologial.meteorological", "Runofriver", "Headrace")
change <- c("Hydro.metering.stations", "Run.of.river", "Headrace")

for (i in 1:length(orig) ) 
  {
      names(techdata)[grep(orig[i], names(techdata))] <- change[i]
}
  
for (i in c("Height", "Breadth", "Area") )
{
    names(techdata)[grep(i, names(techdata))] <- paste("Gate_",names(techdata)[grep(i, names(techdata))], sep="")
}
```



```{r}
#Remove all zero variance and highly correlated variables to reduce the total number of variables and reduce the risk of multicolinearity.

techdata %<>%  mutate_each(funs(numeric),names(.)[sapply(., class)=="integer"])
remove <- nearZeroVar(techdata[,-1])+1
techdata <-  techdata[,-remove]
technum <- sapply(techdata, class)=="numeric"
techdatanum <- techdata[,technum]
techdata <- techdata[,!technum] #the vector is logical
cortest <-cor(techdatanum)
hc = findCorrelation(cortest, cutoff=0.9)
techdata <- cbind(techdata, techdatanum[,-hc])
save(techdata,file ="techdata.R")
```



```{r}
#merge in costs

eidscost <-costjoiner2("Eidsiva", "Eidsiva cost2.xlsx")
ecocost <- costjoiner2("ECO","ECO cost2.xlsx")
statkraftcost <- costjoiner2("Statkraft","Statkraft cost.xlsx")

costdata <- bind_rows(eidscost,ecocost, statkraftcost) %>% select(-WMO_.Rehab,-WMO_Total,-YD_2009,-YD_2010,-YD_2011) %>% gather(key = year, value= cost,-c(Station.ID, WMO_DV)) %>% group_by(Station.ID) %>% summarise(mean_3yr_2014 = mean(cost),WMO_DV = mean(WMO_DV)) %>%filter(!is.na(Station.ID),!is.na(mean_3yr_2014))

data <- inner_join(techdata, costdata, "Station.ID")
```

```{r}
#remove start stops 
data <- filter(data, !is.na(WMO_DV)) 

```


```{r}
#OutPut an R file of the tech data
save(data, file = "WMOData.R")
```